const canvas=document.getElementById('waterfall'),ctx=canvas.getContext('2d'),logPanel=document.getElementById('logPanel'),statsEl=document.getElementById('stats'),toggleBtn=document.getElementById('toggleBtn'),levelFilter=document.getElementById('levelFilter');
const LEVELS=['DEBUG','INFO','WARN','ERROR'],SERVICES=['api-gw','auth-svc','db-proxy','worker','cache'],COLORS={DEBUG:'#444',INFO:'#60a5fa',WARN:'#fbbf24',ERROR:'#f87171'};
let logs=[],paused=false,counts={DEBUG:0,INFO:0,WARN:0,ERROR:0},columns=new Array(60).fill(null).map(()=>({DEBUG:0,INFO:0,WARN:0,ERROR:0}));
function randMsg(lvl){const m={DEBUG:['cache miss key=user:','gc pause 12ms','retry attempt 2'],INFO:['request GET /api/v1/data 200','connection established','job completed id='],WARN:['high latency 450ms','pool near limit 48/50','disk usage 87%'],ERROR:['timeout after 30s','null pointer ref','connection refused']};return m[lvl][Math.floor(Math.random()*3)]+Math.floor(Math.random()*999)}
function genLog(){const lvl=LEVELS[Math.random()<.05?3:Math.random()<.15?2:Math.random()<.5?1:0];const svc=SERVICES[Math.floor(Math.random()*SERVICES.length)];const now=new Date();return{ts:now.toISOString().substr(11,12),level:lvl,service:svc,msg:randMsg(lvl)}}
function addLog(log){logs.push(log);counts[log.level]++;columns[columns.length-1][log.level]++;if(logs.length>500)logs.shift();const f=levelFilter.value;if(f==='all'||f===log.level){const d=document.createElement('div');d.className='log-line '+log.level;d.innerHTML=`<span class="ts">${log.ts}</span> <span class="lvl">[${log.level.padEnd(5)}]</span> <span class="src">${log.service}</span> ${log.msg}`;logPanel.appendChild(d);if(logPanel.children.length>200)logPanel.removeChild(logPanel.firstChild);logPanel.scrollTop=logPanel.scrollHeight}}
function drawWaterfall(){const r=canvas.parentElement.getBoundingClientRect();canvas.width=260;canvas.height=r.height;ctx.fillStyle='#13151e';ctx.fillRect(0,0,260,canvas.height);const bw=4,bh=canvas.height/columns.length;columns.forEach((col,i)=>{const total=col.DEBUG+col.INFO+col.WARN+col.ERROR;if(!total)return;let x=30;['ERROR','WARN','INFO','DEBUG'].forEach(l=>{const w=(col[l]/Math.max(total,1))*220;ctx.fillStyle=COLORS[l];ctx.fillRect(x,i*bh+1,w,bh-2);x+=w})})}
function tick(){columns.push({DEBUG:0,INFO:0,WARN:0,ERROR:0});if(columns.length>60)columns.shift()}
setInterval(()=>{if(!paused){const n=1+Math.floor(Math.random()*4);for(let i=0;i<n;i++)addLog(genLog())}statsEl.textContent=`Total: ${Object.values(counts).reduce((a,b)=>a+b,0)} | E:${counts.ERROR} W:${counts.WARN} I:${counts.INFO} D:${counts.DEBUG}`},300);
setInterval(()=>{if(!paused)tick()},1000);
setInterval(drawWaterfall,200);
toggleBtn.onclick=()=>{paused=!paused;toggleBtn.textContent=paused?'Resume':'Pause'};
levelFilter.onchange=()=>{logPanel.innerHTML='';logs.forEach(l=>{if(levelFilter.value==='all'||levelFilter.value===l.level){const d=document.createElement('div');d.className='log-line '+l.level;d.innerHTML=`<span class="ts">${l.ts}</span> <span class="lvl">[${l.level.padEnd(5)}]</span> <span class="src">${l.service}</span> ${l.msg}`;logPanel.appendChild(d)}})};