const blueCanvas=document.getElementById('blueCanvas'),greenCanvas=document.getElementById('greenCanvas');
const blueFill=document.getElementById('blueFill'),greenFill=document.getElementById('greenFill');
const deployBtn=document.getElementById('deployBtn'),rollbackBtn=document.getElementById('rollbackBtn');
const statusEl=document.getElementById('status'),logEl=document.getElementById('log');
const arrow=document.getElementById('arrow'),nextVerEl=document.getElementById('nextVer');
const blueEnv=document.getElementById('blueEnv'),greenEnv=document.getElementById('greenEnv');
let active='blue',ver=1,blueData=[],greenData=[],deploying=false;
function rps(){return 40+Math.random()*60}
for(let i=0;i<50;i++){blueData.push(rps());greenData.push(0)}
function drawChart(ctx,data,color){ctx.clearRect(0,0,280,100);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((v,i)=>{const x=i*(280/49),y=100-v;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});ctx.stroke()}
function log(msg){const d=document.createElement('div');d.textContent=`[${new Date().toLocaleTimeString()}] ${msg}`;logEl.prepend(d)}
function tick(){blueData.push(active==='blue'?rps():Math.random()*5);blueData.shift();greenData.push(active==='green'?rps():Math.random()*5);greenData.shift();drawChart(blueCanvas.getContext('2d'),blueData,'#60a5fa');drawChart(greenCanvas.getContext('2d'),greenData,'#34d399');requestAnimationFrame(tick)}
deployBtn.onclick=()=>{if(deploying)return;deploying=true;deployBtn.disabled=true;const target=active==='blue'?'green':'blue';const newVer=ver+1;log(`Deploying v${newVer} to ${target}...`);document.querySelector(`.${target} .version`).textContent=`v${newVer} (deploying)`;setTimeout(()=>{log(`v${newVer} health check passed. Switching traffic...`);let pct=0;const iv=setInterval(()=>{pct+=10;if(target==='green'){greenFill.style.width=pct+'%';blueFill.style.width=(100-pct)+'%'}else{blueFill.style.width=pct+'%';greenFill.style.width=(100-pct)+'%'}if(pct>=100){clearInterval(iv);active=target;ver=newVer;deploying=false;deployBtn.disabled=false;rollbackBtn.disabled=false;arrow.className='arrow '+(active==='green'?'right':'left');statusEl.textContent=`Serving: ${active.charAt(0).toUpperCase()+active.slice(1)} (v${ver})`;document.querySelector(`.${target} .version`).textContent=`v${ver}`;document.querySelector(`.${active==='blue'?'green':'blue'} .version`).textContent='standby';blueEnv.classList.toggle('active',active==='blue');greenEnv.classList.toggle('active',active==='green');nextVerEl.textContent=ver+1;log(`Traffic switched to ${active} v${ver}`)}},200)},1500)};
rollbackBtn.onclick=()=>{if(deploying)return;const prev=active==='blue'?'green':'blue';log(`Rolling back to ${prev}...`);active=prev;if(prev==='blue'){blueFill.style.width='100%';greenFill.style.width='0%'}else{greenFill.style.width='100%';blueFill.style.width='0%'}arrow.className='arrow '+(active==='green'?'right':'left');statusEl.textContent=`Serving: ${active.charAt(0).toUpperCase()+active.slice(1)} (v${ver-1})`;blueEnv.classList.toggle('active',active==='blue');greenEnv.classList.toggle('active',active==='green');rollbackBtn.disabled=true;log('Rollback complete')};
blueEnv.classList.add('active');log('System initialized. Blue v1 serving traffic.');tick();