#!/usr/bin/env python3
"""Generate a Mermaid graph of the hub's actual citation network from citations.json.

Layout:
  - Papers (top)        — every PAPER.md
  - Techniques (middle) — every TECHNIQUE.md
  - Atoms (bottom)      — only the atoms that are cited (the long tail of orphans is
                          summarized as a single faded node so the diagram stays readable)

Edges:
  - Technique → Atom    via composes (solid)
  - Paper → Atom        via examines (dashed)
  - Paper → Technique   via examines (dashed)
  - Paper → Paper       via examines (dashed)  — added by schema v0.2.1

Output: docs/citation-graph.mmd (Mermaid `graph LR`). Embed in README via:

  ```mermaid
  %% include docs/citation-graph.mmd
  ```

  or reference directly from the wiki via raw URL.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

HUB_ROOT = Path(__file__).resolve().parents[2]
PAPER_DIR = HUB_ROOT / "paper"
TECHNIQUE_DIR = HUB_ROOT / "technique"
SKILLS_DIR = HUB_ROOT / "skills"
KNOWLEDGE_DIR = HUB_ROOT / "knowledge"
CITATIONS = HUB_ROOT / "citations.json"
OUTPUT = HUB_ROOT / "docs" / "citation-graph.mmd"


def split_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---\n", 4)
    if end == -1:
        return ""
    return text[4 : end + 1]


def parse_frontmatter(path: Path) -> dict:
    fm = split_frontmatter(path.read_text(encoding="utf-8"))
    if not fm:
        return {}
    try:
        return yaml.safe_load(fm) or {}
    except yaml.YAMLError:
        return {}


def safe_id(prefix: str, ref: str) -> str:
    """Mermaid node IDs cannot contain certain chars. Sanitize."""
    sanitized = ref.replace("/", "_").replace("-", "_").replace(".", "_")
    return f"{prefix}_{sanitized}"


def short_label(slug: str, max_len: int = 24) -> str:
    """Trim long slugs for readable nodes."""
    last = slug.rsplit("/", 1)[-1]
    if len(last) <= max_len:
        return last
    return last[: max_len - 1] + "…"


def collect_papers() -> dict[str, dict]:
    out = {}
    for p in sorted(PAPER_DIR.glob("**/PAPER.md")):
        fm = parse_frontmatter(p)
        ref = p.relative_to(PAPER_DIR).parent.as_posix()
        status = (fm.get("status") or "").strip()
        out[ref] = {
            "node_id": safe_id("p", ref),
            "label": short_label(ref),
            "status": status,
            "examines": fm.get("examines") or [],
        }
    return out


def collect_techniques() -> dict[str, dict]:
    out = {}
    for t in sorted(TECHNIQUE_DIR.glob("**/TECHNIQUE.md")):
        fm = parse_frontmatter(t)
        ref = t.relative_to(TECHNIQUE_DIR).parent.as_posix()
        out[ref] = {
            "node_id": safe_id("t", ref),
            "label": short_label(ref),
            "composes": fm.get("composes") or [],
        }
    return out


def load_cited_atoms() -> set[str]:
    """Return set of '<kind>/<ref>' for atoms (skill/knowledge) that are cited."""
    if not CITATIONS.exists():
        return set()
    try:
        data = json.loads(CITATIONS.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return set()
    return {
        k for k in data.get("citations", {}).keys()
        if k.startswith("skill/") or k.startswith("knowledge/")
    }


def render(papers: dict, techniques: dict, cited_atoms: set[str]) -> str:
    lines = [
        "%% Live citation graph generated by bootstrap/tools/_build_citation_graph_mermaid.py",
        "%% Regenerate via precheck.py (post-commit / post-merge git hook).",
        "graph LR",
        "  classDef paperImpl  fill:#a8d8ff,stroke:#2563eb,stroke-width:2px,color:#1e293b",
        "  classDef paperDraft fill:#e0e7ff,stroke:#6366f1,stroke-dasharray:3 3,color:#312e81",
        "  classDef paperRetract fill:#fee2e2,stroke:#dc2626,color:#7f1d1d",
        "  classDef tech       fill:#ccfbf1,stroke:#0d9488,stroke-width:2px,color:#134e4a",
        "  classDef atom       fill:#f1f5f9,stroke:#64748b,color:#334155",
        "  classDef orphans    fill:#fafafa,stroke:#cbd5e1,stroke-dasharray:3 3,color:#94a3b8",
        "",
        "  %% --- Papers ---",
    ]

    for ref, p in papers.items():
        node_id = p["node_id"]
        label = f"📄 {p['label']}"
        lines.append(f'  {node_id}["{label}"]')

    lines.append("")
    lines.append("  %% --- Techniques ---")
    for ref, t in techniques.items():
        lines.append(f'  {t["node_id"]}(["🔗 {t["label"]}"])')

    lines.append("")
    lines.append("  %% --- Cited atoms ---")
    atom_nodes: dict[str, str] = {}
    for key in sorted(cited_atoms):
        kind, ref = key.split("/", 1)
        node_id = safe_id("a", key)
        icon = "⚡" if kind == "skill" else "💡"
        atom_nodes[key] = node_id
        lines.append(f'  {node_id}(("{icon} {short_label(ref, 20)}"))')

    # Orphan atom summary node — render as single faded box if any
    # (we don't enumerate; the count itself is the story)
    lines.append("")
    lines.append("  %% --- Edges: technique → atom (composes) ---")
    for ref, t in techniques.items():
        for entry in t["composes"]:
            if not isinstance(entry, dict):
                continue
            kind = (entry.get("kind") or "").strip()
            target = (entry.get("ref") or "").strip()
            if kind not in ("skill", "knowledge"):
                continue
            key = f"{kind}/{target}"
            if key not in atom_nodes:
                continue
            lines.append(f'  {t["node_id"]} --> {atom_nodes[key]}')

    lines.append("")
    lines.append("  %% --- Edges: paper → * (examines) ---")
    for ref, p in papers.items():
        for entry in p["examines"]:
            if not isinstance(entry, dict):
                continue
            kind = (entry.get("kind") or "").strip()
            target = (entry.get("ref") or "").strip()
            if kind == "paper":
                if target in papers:
                    lines.append(f'  {p["node_id"]} -.-> {papers[target]["node_id"]}')
            elif kind == "technique":
                if target in techniques:
                    lines.append(f'  {p["node_id"]} -.-> {techniques[target]["node_id"]}')
            elif kind in ("skill", "knowledge"):
                key = f"{kind}/{target}"
                if key in atom_nodes:
                    lines.append(f'  {p["node_id"]} -.-> {atom_nodes[key]}')

    lines.append("")
    lines.append("  %% --- Class assignments ---")
    for ref, p in papers.items():
        if p["status"] == "implemented":
            lines.append(f'  class {p["node_id"]} paperImpl')
        elif p["status"] == "retracted":
            lines.append(f'  class {p["node_id"]} paperRetract')
        else:
            lines.append(f'  class {p["node_id"]} paperDraft')
    if techniques:
        joined = ",".join(t["node_id"] for t in techniques.values())
        lines.append(f'  class {joined} tech')
    if atom_nodes:
        joined = ",".join(atom_nodes.values())
        lines.append(f'  class {joined} atom')

    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--output", default=str(OUTPUT))
    p.add_argument("--print", action="store_true", help="Print to stdout instead of writing")
    args = p.parse_args()

    papers = collect_papers()
    techniques = collect_techniques()
    cited_atoms = load_cited_atoms()

    text = render(papers, techniques, cited_atoms)

    if args.print:
        sys.stdout.write(text)
    else:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        rel = out.relative_to(HUB_ROOT) if out.is_relative_to(HUB_ROOT) else out
        print(
            f"Wrote {rel} — {len(papers)} papers, {len(techniques)} techniques, "
            f"{len(cited_atoms)} cited atoms"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
